; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
ResourceCount=0
ExtraDDXCount=33
ExtraDDX1=nMN;;Autodesk Control;CAdUiComboBox;;Control
ExtraDDX2=nMN;;AutoCAD Control;CAcUiComboBox;;Control
ExtraDDX3=nMN;;AutoCAD Control;CAcUiAngleComboBox;;Control
ExtraDDX4=nMN;;AutoCAD Control;CAcUiMRUComboBox;;Control
ExtraDDX5=nMN;;AutoCAD Control;CAcUiArrowHeadComboBox;;Control
ExtraDDX6=nMN;;AutoCAD Control;CAcUiColorComboBox;;Control
ExtraDDX7=nMN;;AutoCAD Control;CAcUiLineWeightComboBox;;Control
ExtraDDX8=nMN;;AutoCAD Control;CAcUiPlotStyleNamesComboBox;;Control
ExtraDDX9=nMN;;AutoCAD Control;CAcUiPlotStyleTableComboBox;;Control
ExtraDDX10=nMN;;Autodesk Control;CAcUiNumericComboBox;;Control
ExtraDDX11=nMN;;AutoCAD Control;CAcUiStringComboBox;;Control
ExtraDDX12=nMN;;AutoCAD Control;CAcUiSymbolComboBox;;Control
ExtraDDX13=lL;;Autodesk Control;CAdUiListBox;;Control
ExtraDDX14=lL;;AutoCAD Control;CAcUiListBox;;Control
ExtraDDX15=lL;;AutoCAD Control;CAcUiMRUListBox;;Control
ExtraDDX16=B;;Autodesk Control;CAdUiOwnerDrawButton;;Control
ExtraDDX17=B;;Autodesk Control;CAdUiBitmapButton;;Control
ExtraDDX18=B;;Autodesk Control;CAdUiBitmapStatic;;Control
ExtraDDX10=B;;Autodesk Control;CAdUiDropSite;;Control
ExtraDDX20=B;;AutoCAD Control;CAcUiDropSite;;Control
ExtraDDX21=B;;AutoCAD Control;CAcUiBitmapStatic;;Control
ExtraDDX22=B;;Autodesk Control;CAdUiToolButton;;Control
ExtraDDX23=B;;AutoCAD Control;CAcUiToolButton;;Control
ExtraDDX24=B;;AutoCAD Control;CAcUiBitmapButton;;Control
ExtraDDX25=B;;AutoCAD Control;CAcUiPickButton;;Control
ExtraDDX26=B;;AutoCAD Control;CAcUiSelectButton;;Control
ExtraDDX27=B;;AutoCAD Control;CAcUiOwnerDrawButton;;Control
ExtraDDX28=E;;Autodesk Control;CAdUiEdit;;Control
ExtraDDX29=E;;AutoCAD Control;CAcUiEdit;;Control
ExtraDDX30=E;;AutoCAD Control;CAcUiAngleEdit;;Control
ExtraDDX31=E;;AutoCAD Control;CAcUiNumericEdit;;Control
ExtraDDX32=E;;AutoCAD Control;CAcUiStringEdit;;Control
ExtraDDX33=E;;AutoCAD Control;CAcUiSymbolEdit;;Control
;ExtraDDX34=X;;Autodesk Control;CAdUiListCtrl;;Control
;ExtraDDX35=X;;AutoCAD Control;CAcUiListCtrl;;Control
;ExtraDDX36=T;;Autodesk Control;CAdUiTab;;Control
;ExtraDDX37=T;;AutoCAD Control;CAcUiTab;;Control
;ExtraDDX38=H;;Autodesk Control;CAdUiHeaderCtrl;;Control
;ExtraDDX39=H;;AutoCAD Control;CAcUiHeaderCtrl;;Control
ClassCount=0
LastClass=
LastTemplate=CDialog
NewFileInclude1=#include "StdAfx.h"
NewFileInclude2=#include "resource.h"
ODLFile=UseReactor.idl
LastPage=0

